import { Scenario, DailyChallenge, SupportedLanguage, Translation } from './types';
import { ROLEPLAY_JOURNEY } from './data/roleplayJourney';
import { 
  Plane, Coffee, Briefcase, GraduationCap, PartyPopper, ShoppingBag, Languages, Utensils, MapPin, 
  BedDouble, Car, Activity, Gamepad2, Heart, Dumbbell, AlertTriangle, Film, Phone, Home, DollarSign, 
  Kanban, Presentation, Users, Laptop, ShieldAlert, UserCheck, Scale, Smile, Siren, Shield, Brain, Wine,
  CarFront, Receipt, Scissors, CloudSun, Stethoscope, Landmark, FileText, FileKey, Cone
} from 'lucide-react';
import React from 'react';

export const UI_TEXT: Record<SupportedLanguage, Translation> = {
  'pt-BR': {
    welcome: 'Bem-vindo',
    hero_title_1: 'Fluência é uma',
    hero_title_2: 'Conversa.',
    hero_desc: 'Mergulhe em simulações em tempo real. O Verba ouve sua pronúncia, corrige erros de verbalização e guia você para a fluência perfeita com IA.',
    start_btn: 'Começar a Praticar',
    level: 'Nível',
    streak: 'Ofensiva',
    xp: 'XP Total',
    streak_msg: 'Você está pegando fogo! 🔥',
    xp_msg: 'Top 5% dos alunos',
    daily_quests: 'Missões Diárias',
    practice_scenarios: 'Jornada de Fluência',
    choose_scenario: 'Escolha seu Cenário',
    all: 'Todos',
    beginner: 'Iniciante',
    intermediate: 'Intermediário',
    advanced: 'Avançado',
    live_btn: 'Voz',
    chat_btn: 'Chat',
    footer: 'Verba AI. Fluência através da tecnologia.',
    api_missing: 'Chave API Ausente',
    api_missing_desc: 'Este aplicativo requer uma chave API do Google Gemini para funcionar.',
    toast_level: 'Subiu de Nível!',
    toast_quest: 'Missão Completa',
    input_placeholder: 'Digite sua mensagem...',
    ai_disclaimer: 'A IA pode cometer erros. Verifique informações importantes.',
    suggested_responses: 'Dicas do que falar',
    feedback_title: 'Feedback do Verba',
    listening: 'OUVINDO...',
    speaking: 'VERBA FALANDO...',
    ready: 'PRONTO',
    connecting: 'Conectando ao Coach...',
    error_conn: 'Erro de conexão.',
    retry: 'Tentar Novamente',
    interface_lang: 'Idioma do App',
    learning_lang: 'Quero aprender',
    next_phrase: 'Próxima Frase',
    prev_phrase: 'Anterior',
    script_mode: 'Roteiro de Fala',
    hint_button: 'Dica',
    locked: 'Bloqueado',
    complete_prev: 'Complete a anterior',
    finish_lesson: 'Concluir Lição',
    lesson_complete: 'Lição Completa!',
    continue: 'Continuar'
  },
  'en-US': {
    welcome: 'Welcome',
    hero_title_1: 'Fluency is a',
    hero_title_2: 'Conversation.',
    hero_desc: 'Immerse yourself in real-time roleplay. Verba listens, corrects pronunciation, and guides you to perfect fluency with instant AI feedback.',
    start_btn: 'Start Speaking',
    level: 'Level',
    streak: 'Streak',
    xp: 'Total XP',
    streak_msg: "You're on fire! 🔥",
    xp_msg: 'Top 5% of learners',
    daily_quests: 'Daily Quests',
    practice_scenarios: 'Fluency Journey',
    choose_scenario: 'Choose Your Scenario',
    all: 'All',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    live_btn: 'Live',
    chat_btn: 'Chat',
    footer: 'Verba AI. Fluency through technology.',
    api_missing: 'API Key Missing',
    api_missing_desc: 'This application requires a Google Gemini API key to function.',
    toast_level: 'Level Up!',
    toast_quest: 'Quest Complete',
    input_placeholder: 'Type your message...',
    ai_disclaimer: 'AI can make mistakes. Check important info.',
    suggested_responses: 'Suggested Responses',
    feedback_title: 'Verba Feedback',
    listening: 'LISTENING...',
    speaking: 'VERBA SPEAKING...',
    ready: 'READY',
    connecting: 'Connecting to Verba...',
    error_conn: 'Connection error.',
    retry: 'Retry',
    interface_lang: 'Interface',
    learning_lang: 'I want to learn',
    next_phrase: 'Next Phrase',
    prev_phrase: 'Previous',
    script_mode: 'Speaking Script',
    hint_button: 'Hint',
    locked: 'Locked',
    complete_prev: 'Complete previous',
    finish_lesson: 'Finish Lesson',
    lesson_complete: 'Lesson Complete!',
    continue: 'Continue'
  },
  'es-ES': {
    welcome: 'Bienvenido',
    hero_title_1: 'La fluidez es una',
    hero_title_2: 'Conversación.',
    hero_desc: 'Sumérgete en juegos de rol en tiempo real. Verba escucha tu pronunciación, corrige errores y te guía hacia la fluidez perfecta.',
    start_btn: 'Empezar a Hablar',
    level: 'Nivel',
    streak: 'Racha',
    xp: 'XP Total',
    streak_msg: '¡Estás en racha! 🔥',
    xp_msg: 'Top 5% de estudiantes',
    daily_quests: 'Misiones Diarias',
    practice_scenarios: 'Jornada de Fluidez',
    choose_scenario: 'Elige tu Escenario',
    all: 'Todos',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzado',
    live_btn: 'En Vivo',
    chat_btn: 'Chat',
    footer: 'Verba AI. Fluidez a través de la tecnología.',
    api_missing: 'Falta Clave API',
    api_missing_desc: 'Esta aplicación requiere una clave API de Google Gemini para funcionar.',
    toast_level: '¡Subiste de Nivel!',
    toast_quest: 'Misión Completa',
    input_placeholder: 'Escribe tu mensaje...',
    ai_disclaimer: 'La IA puede cometer errores.',
    suggested_responses: 'Respuestas Sugeridas',
    feedback_title: 'Comentarios de Verba',
    listening: 'ESCUCHANDO...',
    speaking: 'VERBA HABLANDO...',
    ready: 'LISTO',
    connecting: 'Conectando a Verba...',
    error_conn: 'Error de conexión.',
    retry: 'Reintentar',
    interface_lang: 'Interfaz',
    learning_lang: 'Quiero aprender',
    next_phrase: 'Siguiente Frase',
    prev_phrase: 'Anterior',
    script_mode: 'Guion de Voz',
    hint_button: 'Pista',
    locked: 'Bloqueado',
    complete_prev: 'Completar anterior',
    finish_lesson: 'Terminar Lección',
    lesson_complete: '¡Lección Completa!',
    continue: 'Continuar'
  },
  'de-DE': {
    welcome: 'Willkommen',
    hero_title_1: 'Flüssigkeit ist ein',
    hero_title_2: 'Gespräch.',
    hero_desc: 'Tauchen Sie in Echtzeit-Rollenspiele ein. Verba hört auf Ihre Aussprache, korrigiert Fehler und führt Sie zur perfekten Sprachfertigkeit.',
    start_btn: 'Sprechen beginnen',
    level: 'Stufe',
    streak: 'Serie',
    xp: 'Gesamt XP',
    streak_msg: 'Du bist heiß! 🔥',
    xp_msg: 'Top 5% der Lernenden',
    daily_quests: 'Tägliche Quests',
    practice_scenarios: 'Szenarien',
    choose_scenario: 'Wählen Sie Ihr Szenario',
    all: 'Alle',
    beginner: 'Anfänger',
    intermediate: 'Mittelstufe',
    advanced: 'Fortgeschritten',
    live_btn: 'Live',
    chat_btn: 'Chat',
    footer: 'Verba AI. Fließend durch Technologie.',
    api_missing: 'API-Key fehlt',
    api_missing_desc: 'Diese Anwendung benötigt einen Google Gemini API-Key.',
    toast_level: 'Level Up!',
    toast_quest: 'Quest abgeschlossen',
    input_placeholder: 'Schreibe eine Nachricht...',
    ai_disclaimer: 'KI kann Fehler machen.',
    suggested_responses: 'Vorgeschlagene Antworten',
    feedback_title: 'Verba Feedback',
    listening: 'HÖREN...',
    speaking: 'VERBA SPRICHT...',
    ready: 'BEREIT',
    connecting: 'Verbindung zu Verba...',
    error_conn: 'Verbindungsfehler.',
    retry: 'Wiederholen',
    interface_lang: 'Schnittstelle',
    learning_lang: 'Ich möchte lernen',
    next_phrase: 'Nächster Satz',
    prev_phrase: 'Zurück',
    script_mode: 'Sprechskript',
    hint_button: 'Hinweis',
    locked: 'Gesperrt',
    complete_prev: 'Vorheriges abschließen',
    finish_lesson: 'Lektion beenden',
    lesson_complete: 'Lektion abgeschlossen!',
    continue: 'Weiter'
  },
  'it-IT': {
    welcome: 'Benvenuto',
    hero_title_1: 'La fluidità è una',
    hero_title_2: 'Conversazione.',
    hero_desc: 'Immergiti in giochi di ruolo in tempo real. Verba ascolta la tua pronuncia, corregge gli errori e ti guida verso la perfetta fluidità.',
    start_btn: 'Inizia a parlare',
    level: 'Livello',
    streak: 'Serie',
    xp: 'XP Totali',
    streak_msg: 'Sei fortissimo! 🔥',
    xp_msg: 'Top 5% degli studenti',
    daily_quests: 'Missioni giornaliere',
    practice_scenarios: 'Scenari',
    choose_scenario: 'Scegli il tuo scenario',
    all: 'Tutti',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzato',
    live_btn: 'Dal vivo',
    chat_btn: 'Chat',
    footer: 'Verba AI. Fluidità attraverso la tecnologia.',
    api_missing: 'Chiave API mancante',
    api_missing_desc: 'Questa applicazione richiede una chiave API di Google Gemini.',
    toast_level: 'Livello completato!',
    toast_quest: 'Missione completata',
    input_placeholder: 'Scrivi un messaggio...',
    ai_disclaimer: 'L\'IA può commettere errori.',
    suggested_responses: 'Risposte suggerite',
    feedback_title: 'Feedback di Verba',
    listening: 'ASCOLTO...',
    speaking: 'VERBA PARLA...',
    ready: 'PRONTO',
    connecting: 'Connessione a Verba...',
    error_conn: 'Errore di connessione.',
    retry: 'Riprova',
    interface_lang: 'Interfaccia',
    learning_lang: 'Voglio imparare',
    next_phrase: 'Frase successiva',
    prev_phrase: 'Precedente',
    script_mode: 'Copione',
    hint_button: 'Suggerimento',
    locked: 'Bloccato',
    complete_prev: 'Completa precedente',
    finish_lesson: 'Termina lezione',
    lesson_complete: 'Lezione completata!',
    continue: 'Continua'
  },
  'ru-RU': {
    welcome: 'Добро пожаловать',
    hero_title_1: 'Беглость — это',
    hero_title_2: 'Разговор.',
    hero_desc: 'Погрузитесь в ролевые игры в реальном времени. Verba слушает ваше произношение, исправляет ошибки и ведет вас к совершенному владению языком.',
    start_btn: 'Начать говорить',
    level: 'Уровень',
    streak: 'Серия',
    xp: 'Всего XP',
    streak_msg: 'Вы в ударе! 🔥',
    xp_msg: 'Лучшие 5% учеников',
    daily_quests: 'Ежедневные задания',
    practice_scenarios: 'Сценарии',
    choose_scenario: 'Выберите сценарий',
    all: 'Все',
    beginner: 'Новичок',
    intermediate: 'Средний',
    advanced: 'Продвинутый',
    live_btn: 'Вживую',
    chat_btn: 'Чат',
    footer: 'Verba AI. Беглость через технологии.',
    api_missing: 'Отсутствует API-ключ',
    api_missing_desc: 'Для работы приложения требуется API-ключ Google Gemini.',
    toast_level: 'Новый уровень!',
    toast_quest: 'Задание выполнено',
    input_placeholder: 'Введите сообщение...',
    ai_disclaimer: 'ИИ может ошибаться.',
    suggested_responses: 'Варианты ответов',
    feedback_title: 'Обратная связь Verba',
    listening: 'СЛУШАЮ...',
    speaking: 'VERBA ГОВОРИТ...',
    ready: 'ГОТОВ',
    connecting: 'Подключение к Verba...',
    error_conn: 'Ошибка подключения.',
    retry: 'Повторить',
    interface_lang: 'Интерфейс',
    learning_lang: 'Я хочу учить',
    next_phrase: 'След. фраза',
    prev_phrase: 'Назад',
    script_mode: 'Сценарий',
    hint_button: 'Подсказка',
    locked: 'Заблокировано',
    complete_prev: 'Завершите пред.',
    finish_lesson: 'Завершить урок',
    lesson_complete: 'Урок завершен!',
    continue: 'Продолжить'
  }
};

const LANG_NAMES: Record<SupportedLanguage, string> = {
  'en-US': 'English',
  'pt-BR': 'Portuguese',
  'es-ES': 'Spanish',
  'de-DE': 'German',
  'it-IT': 'Italian',
  'ru-RU': 'Russian'
};

export const getIcon = (name: string) => {
  const icons: Record<string, React.ReactNode> = {
    Coffee: <Coffee className="w-6 h-6" />,
    Briefcase: <Briefcase className="w-6 h-6" />,
    Plane: <Plane className="w-6 h-6" />,
    ShoppingBag: <ShoppingBag className="w-6 h-6" />,
    GraduationCap: <GraduationCap className="w-6 h-6" />,
    PartyPopper: <PartyPopper className="w-6 h-6" />,
    Utensils: <Utensils className="w-6 h-6" />,
    MapPin: <MapPin className="w-6 h-6" />,
    BedDouble: <BedDouble className="w-6 h-6" />,
    Car: <Car className="w-6 h-6" />,
    Activity: <Activity className="w-6 h-6" />,
    Gamepad2: <Gamepad2 className="w-6 h-6" />,
    Heart: <Heart className="w-6 h-6" />,
    Dumbbell: <Dumbbell className="w-6 h-6" />,
    AlertTriangle: <AlertTriangle className="w-6 h-6" />,
    Film: <Film className="w-6 h-6" />,
    Phone: <Phone className="w-6 h-6" />,
    Home: <Home className="w-6 h-6" />,
    DollarSign: <DollarSign className="w-6 h-6" />,
    Kanban: <Kanban className="w-6 h-6" />,
    Presentation: <Presentation className="w-6 h-6" />,
    Users: <Users className="w-6 h-6" />,
    Laptop: <Laptop className="w-6 h-6" />,
    ShieldAlert: <ShieldAlert className="w-6 h-6" />,
    UserCheck: <UserCheck className="w-6 h-6" />,
    Scale: <Scale className="w-6 h-6" />,
    Smile: <Smile className="w-6 h-6" />,
    Siren: <Siren className="w-6 h-6" />,
    Shield: <Shield className="w-6 h-6" />,
    Brain: <Brain className="w-6 h-6" />,
    Wine: <Wine className="w-6 h-6" />,
    CarFront: <CarFront className="w-6 h-6" />,
    Receipt: <Receipt className="w-6 h-6" />,
    Scissors: <Scissors className="w-6 h-6" />,
    CloudSun: <CloudSun className="w-6 h-6" />,
    Stethoscope: <Stethoscope className="w-6 h-6" />,
    Landmark: <Landmark className="w-6 h-6" />,
    FileText: <FileText className="w-6 h-6" />,
    FileKey: <FileKey className="w-6 h-6" />,
    Cone: <Cone className="w-6 h-6" />
  };
  return icons[name] || <Languages className="w-6 h-6" />;
};

export const getScenarios = (lang: SupportedLanguage): Scenario[] => {
  const targetLangName = LANG_NAMES[lang];
  
  return ROLEPLAY_JOURNEY.map(item => ({
    id: item.id,
    title: item.title,
    description: item.description,
    icon: item.icon,
    color: item.color,
    difficulty: item.level as Scenario['difficulty'],
    hints: item.hints,
    systemInstruction: `
      You are an English teacher and roleplay partner for a ${LANG_NAMES['pt-BR']} speaker learning ${targetLangName}.
      SCENARIO: ${item.title}
      DESCRIPTION: ${item.description}
      LEVEL: ${item.level}
      
      YOUR ROLE:
      1. Act as the character in the scenario (e.g. barista, interviewer, friend).
      2. Follow the user's script if they are following it, but be flexible if they improvise.
      3. The user has a script they are trying to say. If they say it correctly, continue the conversation naturally.
      4. If they struggle with pronunciation or grammar, give a quick, gentle tip in ${LANG_NAMES['pt-BR']}, then prompt them to try again in ${targetLangName}.
      
      SCRIPT CONTEXT (The user is trying to say these lines):
      ${item.script ? item.script.map(s => `- ${s.original}`).join('\n') : 'No specific script, free conversation.'}
    `,
    script: item.script // Now passing the script correctly!
  }));
};

export const getChallenges = (lang: SupportedLanguage): DailyChallenge[] => {
  const t = UI_TEXT[lang];
  return [
    { id: '1', title: 'Falador do Chat', description: 'Envie 5 mensagens hoje', target: 5, current: 0, completed: false, reward: 50, type: 'chat' },
    { id: '2', title: 'Mestre da Voz', description: 'Complete 1 roteiro de voz', target: 1, current: 0, completed: false, reward: 100, type: 'live' },
    { id: '3', title: 'Gramática Perfeita', description: '3 acertos seguidos', target: 3, current: 0, completed: false, reward: 150, type: 'perfect_grammar' }
  ];
};